In [ ]:
#1D 2D 3D arrays
import numpy as np
arr1 = np.array([2,4,6,8])
print("1D array:", arr1)

arr2 = np.array([[1,2,3],[4,5,6]])
print("2D array:\n", arr2)

arr3 = np.array([[2,4,6], [1,3,5], [1,2,3]])
print("3D array:\n", arr3)


1D array: [2 4 6 8]
2D array:
 [[1 2 3]
 [4 5 6]]
3D array:
 [[2 4 6]
 [1 3 5]
 [1 2 3]]


In [12]:
#Zeros array
zeros_array = np.zeros((3,3))
print("Array of zeros:\n", zeros_array)

#Ones array
ones_array = np.ones((3,3))
print("array of ones:\n", ones_array)

#Full array
full_array = np.full((3,3), 5)
print("Array filled with 5:\n", full_array)

#identity matrix
identity_arr = np.eye(4)
print("Identity matrix:\n", identity_arr)


Array of zeros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
array of ones:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Array filled with 5:
 [[5 5 5]
 [5 5 5]
 [5 5 5]]
Identity matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
#Array with range and linspace
range_array = np.arange(0,10,2)
print("Array with range from 0 to 10 with step 2:\n", range_array)

#Array with linspace
linspace_array = np.linspace(0,1,5)
print("Linspace array", linspace_array)

#Random arrays
random_array = np.random.rand(3,3)
randomint_array = np.random.randint(0,10,(3,3))
print("Random float array:\n", random_array)
print("Random integer array:\n", randomint_array)


Array with range from 0 to 10 with step 2:
 [0 2 4 6 8]
linespace array [0.   0.25 0.5  0.75 1.  ]
Random float array:
 [[0.63880029 0.47425338 0.60843385]
 [0.54892272 0.58961412 0.47073604]
 [0.20330745 0.27727611 0.83970068]]
Random integer array:
 [[7 7 1]
 [0 9 6]
 [6 6 2]]


In [ ]:
sample_array = np.random.choice([1,2,3,4,5], size=(3,3))
print("array:\n", sample_array)
print("array shape:", sample_array.shape)
print("array size:", sample_array.size)
